### ISSUE TITLE
Не працює в alpine

### ISSUE THREAD

**Issue by Gorp** [Yneth/distress-releases#1]
Я маю таку помилку

```
./distress_x86_64-unknown-linux-gnu 
zsh: no such file or directory: ./distress_x86_64-unknown-linux-gnu

```

Сам файл є, схоже що немає якоїсь утіліти, що використовується

**Comment by Yneth** [comment]
@Gorp не забудьте додати можливість виконувати файл
`chmod +x distress_x86_64-unknown-linux-gnu `

**Comment by vadyochik** [comment]
справа зовсім не в execute bit. воно майже ніде не запускається. пробував осатанні версії alpine, debian, ubuntu, oracle linux. зроби статікалі лінкед бінарі, або докер імадж.

bash-5.1# ldd ./distress_x86_64-unknown-linux-gnu                                                                             
        /lib64/ld-linux-x86-64.so.2 (0x7f40a9c22000)                                         
        libssl.so.1.1 => /lib/libssl.so.1.1 (0x7f40a96a5000)                                    
        libcrypto.so.1.1 => /lib/libcrypto.so.1.1 (0x7f40a9423000)                               
Error loading shared library libgcc_s.so.1: No such file or directory (needed by ./distress_x86_64-unknown-linux-gnu)     
        libpthread.so.0 => /lib64/ld-linux-x86-64.so.2 (0x7f40a9c22000)                                                      
        libm.so.6 => /lib64/ld-linux-x86-64.so.2 (0x7f40a9c22000)        
        libdl.so.2 => /lib64/ld-linux-x86-64.so.2 (0x7f40a9c22000)
        libc.so.6 => /lib64/ld-linux-x86-64.so.2 (0x7f40a9c22000)                                                                                                                 
Error relocating ./distress_x86_64-unknown-linux-gnu: __register_atfork: symbol not found                                                                                         
Error relocating ./distress_x86_64-unknown-linux-gnu: _Unwind_Resume: symbol not found                                                                                            
Error relocating ./distress_x86_64-unknown-linux-gnu: _Unwind_Backtrace: symbol not found   
Error relocating ./distress_x86_64-unknown-linux-gnu: _Unwind_GetIP: symbol not found                                                                                             
Error relocating ./distress_x86_64-unknown-linux-gnu: gnu_get_libc_version: symbol not found                                                                                      
Error relocating ./distress_x86_64-unknown-linux-gnu: __res_init: symbol not found                                                                                                
bash-5.1#

root@1f21c920bbbf:~# ldd ./distress_x86_64-unknown-linux-gnu 
        linux-vdso.so.1 (0x00007ffc39863000)
        libssl.so.1.1 => not found
        libcrypto.so.1.1 => not found
        libgcc_s.so.1 => /lib/x86_64-linux-gnu/libgcc_s.so.1 (0x00007fa9b829c000)
        libpthread.so.0 => /lib/x86_64-linux-gnu/libpthread.so.0 (0x00007fa9b8297000)
        libm.so.6 => /lib/x86_64-linux-gnu/libm.so.6 (0x00007fa9b81b0000)
        libdl.so.2 => /lib/x86_64-linux-gnu/libdl.so.2 (0x00007fa9b81a9000)
        libc.so.6 => /lib/x86_64-linux-gnu/libc.so.6 (0x00007fa9b7f81000)
        /lib64/ld-linux-x86-64.so.2 (0x00007fa9b87bc000)
root@1f21c920bbbf:~#

**Comment by vadyochik** [comment]
root@7dc9e3418ca3:/# chmod +x distress_x86_64-unknown-linux-gnu 
root@7dc9e3418ca3:/# ./distress_x86_64-unknown-linux-gnu 
2022-06-09 23:05:54 INFO - bin_updater| started
2022-06-09 23:05:54 INFO - main| initializing context...
2022-06-09 23:05:54 ERROR - main| failed to due to error, reason ReqwestError(reqwest::Error { kind: Decode, source: Error("invalid uri character", line: 6687, column: 2) })  src/main.rs:87
2022-06-09 23:05:54 INFO - bin_updater| child exited with status Ok(ExitStatus(unix_wait_status(256)))
2022-06-09 23:05:54 INFO - bin_updater| shutting down... it can take a couple of seconds
root@7dc9e3418ca3:/# cat /etc/os-release 
NAME="Ubuntu"
VERSION="20.04.4 LTS (Focal Fossa)"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu 20.04.4 LTS"
VERSION_ID="20.04"
HOME_URL="https://www.ubuntu.com/"
SUPPORT_URL="https://help.ubuntu.com/"
BUG_REPORT_URL="https://bugs.launchpad.net/ubuntu/"
PRIVACY_POLICY_URL="https://www.ubuntu.com/legal/terms-and-policies/privacy-policy"
VERSION_CODENAME=focal
UBUNTU_CODENAME=focal
root@7dc9e3418ca3:/# arch 
x86_64
root@7dc9e3418ca3:/# ldd ./distress_x86_64-unknown-linux-gnu 
        linux-vdso.so.1 (0x00007ffd7a7a6000)
        libssl.so.1.1 => /lib/x86_64-linux-gnu/libssl.so.1.1 (0x00007ffbcbdda000)
        libcrypto.so.1.1 => /lib/x86_64-linux-gnu/libcrypto.so.1.1 (0x00007ffbcbb04000)
        libgcc_s.so.1 => /lib/x86_64-linux-gnu/libgcc_s.so.1 (0x00007ffbcbae9000)
        libpthread.so.0 => /lib/x86_64-linux-gnu/libpthread.so.0 (0x00007ffbcbac6000)
        libm.so.6 => /lib/x86_64-linux-gnu/libm.so.6 (0x00007ffbcb977000)
        libdl.so.2 => /lib/x86_64-linux-gnu/libdl.so.2 (0x00007ffbcb971000)
        libc.so.6 => /lib/x86_64-linux-gnu/libc.so.6 (0x00007ffbcb77d000)
        /lib64/ld-linux-x86-64.so.2 (0x00007ffbcc36d000)
root@7dc9e3418ca3:/#

**Comment by Yneth** [comment]
@vadyochik кк на вихідних додам

**Comment by Yneth** [comment]
> ```
> root@7dc9e3418ca3:/# chmod +x distress_x86_64-unknown-linux-gnu 
> root@7dc9e3418ca3:/# ./distress_x86_64-unknown-linux-gnu 
> 2022-06-09 23:05:54 INFO - bin_updater| started
> 2022-06-09 23:05:54 INFO - main| initializing context...
> 2022-06-09 23:05:54 ERROR - main| failed to due to error, reason ReqwestError(reqwest::Error { kind: Decode, source: Error("invalid uri character", line: 6687, column: 2) })  src/main.rs:87
> 2022-06-09 23:05:54 INFO - bin_updater| child exited with status Ok(ExitStatus(unix_wait_status(256)))
> 2022-06-09 23:05:54 INFO - bin_updater| shutting down... it can take a couple of seconds
> root@7dc9e3418ca3:/# cat /etc/os-release 
> NAME="Ubuntu"
> VERSION="20.04.4 LTS (Focal Fossa)"
> ID=ubuntu
> ID_LIKE=debian
> PRETTY_NAME="Ubuntu 20.04.4 LTS"
> VERSION_ID="20.04"
> HOME_URL="https://www.ubuntu.com/"
> SUPPORT_URL="https://help.ubuntu.com/"
> BUG_REPORT_URL="https://bugs.launchpad.net/ubuntu/"
> PRIVACY_POLICY_URL="https://www.ubuntu.com/legal/terms-and-policies/privacy-policy"
> VERSION_CODENAME=focal
> UBUNTU_CODENAME=focal
> root@7dc9e3418ca3:/# arch 
> x86_64
> root@7dc9e3418ca3:/# ldd ./distress_x86_64-unknown-linux-gnu 
>         linux-vdso.so.1 (0x00007ffd7a7a6000)
>         libssl.so.1.1 => /lib/x86_64-linux-gnu/libssl.so.1.1 (0x00007ffbcbdda000)
>         libcrypto.so.1.1 => /lib/x86_64-linux-gnu/libcrypto.so.1.1 (0x00007ffbcbb04000)
>         libgcc_s.so.1 => /lib/x86_64-linux-gnu/libgcc_s.so.1 (0x00007ffbcbae9000)
>         libpthread.so.0 => /lib/x86_64-linux-gnu/libpthread.so.0 (0x00007ffbcbac6000)
>         libm.so.6 => /lib/x86_64-linux-gnu/libm.so.6 (0x00007ffbcb977000)
>         libdl.so.2 => /lib/x86_64-linux-gnu/libdl.so.2 (0x00007ffbcb971000)
>         libc.so.6 => /lib/x86_64-linux-gnu/libc.so.6 (0x00007ffbcb77d000)
>         /lib64/ld-linux-x86-64.so.2 (0x00007ffbcc36d000)
> root@7dc9e3418ca3:/# 
> ```

цю вже пофіксив

**Comment by vadyochik** [comment]
але ж тепер ось таке:

```
root@e26960217635:~# ./distress_x86_64-unknown-linux-gnu 
2022-06-13 02:33:41 INFO - bin_updater| started
2022-06-13 02:33:41 INFO - main| initializing context...
2022-06-13 02:33:41 ERROR - main| failed to due to error, reason ReqwestError(reqwest::Error { kind: Decode, source: Error("invalid type: integer `404`, expected a sequence", line: 1, column: 3) })  src/main.rs:90
2022-06-13 02:33:41 INFO - bin_updater| child exited with status Ok(ExitStatus(unix_wait_status(256)))
2022-06-13 02:33:41 INFO - bin_updater| shutting down... it can take a couple of seconds
root@e26960217635:~#
```

**Comment by Yneth** [comment]
росіяни зарепортили лінку з цілями
https://gist.github.com/ddosukraine2022/f739250dba308a7a2215617b17114be9

наразі не так багато часу, але постараюсь виправити сьогодні, дякую за терпіння!
