### ISSUE TITLE
index out of bounds: the len is 46 but the index is 95

### ISSUE THREAD

**Issue by kbarkati** [Yneth/distress-releases#19]
{"type":"STOPPED","moduleName":"DISTRESS","timestamp":1704061436688,"message":"Module DISTRESS stopped"}
{"type":"STARTED","moduleName":"DISTRESS","timestamp":1704062216394,"message":"Module DISTRESS started"}
{"type":"STOPPED","moduleName":"DISTRESS","timestamp":1704062280846,"message":"Module DISTRESS stopped"}
{"type":"STARTED","moduleName":"DISTRESS","timestamp":1704062291847,"message":"Module DISTRESS started"}
{"type":"STOPPED","moduleName":"DISTRESS","timestamp":1704062308635,"message":"Module DISTRESS stopped"}
{"type":"STARTED","moduleName":"DISTRESS","timestamp":1704104783122,"message":"Module DISTRESS started"}
{"type":"STOPPED","moduleName":"DISTRESS","timestamp":1704127652922,"message":"Module DISTRESS stopped"}
{"type":"STARTED","moduleName":"DISTRESS","timestamp":1704127659137,"message":"Module DISTRESS started"}
{"type":"STOPPED","moduleName":"DISTRESS","timestamp":1704131294247,"message":"Module DISTRESS stopped"}
{"type":"STARTED","moduleName":"DISTRESS","timestamp":1704138270705,"message":"Module DISTRESS started"}
{"type":"STARTED","moduleName":"DISTRESS","timestamp":1704183793944,"message":"Module DISTRESS started"}
{"type":"STOPPED","moduleName":"DISTRESS","timestamp":1704186355801,"message":"Module DISTRESS stopped"}
{"type":"STARTED","moduleName":"DISTRESS","timestamp":1704196754771,"message":"Module DISTRESS started"}
{"type":"STARTED","moduleName":"DISTRESS","timestamp":1704225245811,"message":"Module DISTRESS started"}
{"type":"STOPPED","moduleName":"DISTRESS","timestamp":1704226871511,"message":"Module DISTRESS stopped"}
{"type":"STARTED","moduleName":"DISTRESS","timestamp":1704233270123,"message":"Module DISTRESS started"}
{"type":"STOPPED","moduleName":"DISTRESS","timestamp":1704235515214,"message":"Module DISTRESS stopped"}
{"type":"STARTED","moduleName":"DISTRESS","timestamp":1704235596392,"message":"Module DISTRESS started"}
{"type":"STARTED","moduleName":"DISTRESS","timestamp":1704287967575,"message":"Module DISTRESS started"}
{ "level":"INFO", "date":"2024-01-03 14:19:27", "msg":"main| starting distress:0.7.11 for any questions or support refer to: https://t.me/distress_support" }
{ "level":"INFO", "date":"2024-01-03 14:19:27", "msg":"main| initializing context..." }
{ "level":"WARN", "date":"2024-01-03 14:19:28", "msg":"packet flood is not allowed, reason: "OpenSocketFailed(Os { code: 1, kind: PermissionDenied, message: \"Operation not permitted\" })"" }
thread 'main' panicked at 'index out of bounds: the len is 46 but the index is 95', /Users/runner/.cargo/registry/src/index.crates.io-6f17d22bba15001f/default-net-0.14.1/src/interface/unix.rs:178:17

Please track this error here: 
		https://t.me/distress_support

or
		https://github.com/Yneth/distress-releases/issues
additional info: 
	platform=distress_x86_64-apple-darwin
	version=0.7.11

{"type":"STOPPED","moduleName":"DISTRESS","timestamp":1704287968704,"message":"Module DISTRESS stopped"}

**Comment by Yneth** [comment]
should be fixed in 0.7.12
