### ISSUE TITLE
Sqlite error 

### ISSUE THREAD

**Issue by rrailian-hv** [Yneth/distress-releases#8]
✦ ➜ ./distress_x86_64-apple-darwin -c 2048
2022-07-08 12:44:14 INFO - bin_updater| started
2022-07-08 12:44:15 INFO - bin_updater| no new version ("0.2.2"), skipping...
2022-07-08 12:44:15 INFO - main| initializing context...
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: TorError(Error { detail: DirMgr(Bug(Bug(BugRepr { message: "sqlite detected bug", location: Location { file: "/Users/runner/.cargo/registry/src/github.com-1ecc6299db9ec823/tor-dirmgr-0.5.0/src/err.rs", line: 286, col: 17 }, backtrace: Captured(   0: __mh_execute_header
   1: __mh_execute_header
   2: __mh_execute_header
   3: __mh_execute_header
   4: __mh_execute_header
   5: __mh_execute_header
   6: __mh_execute_header
   7: __mh_execute_header
   8: __mh_execute_header
   9: __mh_execute_header
  10: __mh_execute_header
  11: __mh_execute_header
), source: Some(SqliteFailure(Error { code: ReadOnly, extended_code: 8 }, Some("attempt to write a readonly database"))), kind: Internal }))) })', src/main.rs:67:16

Please track this error here:
		https://github.com/Yneth/distress-releases/issues
or
		https://discord.gg/rWTNk3UR
additional info:
	platform=distress_x86_64-apple-darwin
	version=0.2.2

2022-07-08 12:44:28 INFO - bin_updater| child exited with status Ok(ExitStatus(unix_wait_status(6)))
2022-07-08 12:44:28 INFO - bin_updater| shutting down... it can take a couple of seconds

**Comment by Yneth** [comment]
checking..., unfortunately tor client for rust is still in development in a bit buggy, will try to fix.

this issue could be resolved by restarting a couple of times
